# Generated by Django 4.2.13 on 2024-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_ip', models.CharField(max_length=200)),
                ('greetings', models.CharField(max_length=500)),
            ],
        ),
    ]
